import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFile, mkdir } from "fs/promises";

const outputDir = "dist";

async function copyStaticAssets() {
	await mkdir(outputDir, { recursive: true });
	await Promise.all([
		copyFile("manifest.json", `${outputDir}/manifest.json`),
		copyFile("styles.css", `${outputDir}/styles.css`),
	]);
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

await mkdir(outputDir, { recursive: true });

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outputDir}/main.js`,
	loader: { '.md': 'text' },
});

if (prod) {
	await context.rebuild();
	await copyStaticAssets();
	process.exit(0);
} else {
	await copyStaticAssets();
	await context.watch();
}
